# Site settings
title: 咖咔屋
SEOTitle: 咖咔屋 | 分享有趣和好玩儿的
header-img: "img/home-bg.webp"
email: locyoo@gmail.com
description: "菩提本无树，何处惹尘埃"
keyword: "咖咔屋, kkkwu"
url: "kkkwu.com" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username_none: locyoo
#weibo_username_u: locyoo
#zhihu_username: locyoo
#github_username: locyoo
#twitter_username: locyoo
#facebook_username:  locyoo 
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: xiaoleee

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # 是否使用侧栏
sidebar-about-description: "菩提本无树，何处惹尘埃"
sidebar-avatar: /img/3062d3d016581.jpg # 使用绝对路径，绝对路径是从根目录的文件夹开始直到目标的文件

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 2 # 如果标签使用的次数大于指定的值，则会出现在右侧

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "荒岛", href: "https://lala.im/" },
    { title: "VPS大玩家", href: "https://www.vpsdawanjia.com/" },
    { title: "Jason", href: "https://blog.carjaswong.com/" },
    { title: "心语家园", href: "https://www.xinyucn.cc/" },
    { title: "虚拟号", href: "https://xunihao.net/" },
    { title: "果核剥壳", href: "https://www.ghxi.com/" },
    { title: "字节智造", href: "https://www.zsxcool.com/" },
    { title: "全历史", href: "https://www.allhistory.com/" },
    { title: "小叽资源", href: "https://steamzg.com/" },
    { title: "福利吧", href: "https://fuliba2023.net/" },
    { title: "小霸王游戏", href: "https://www.yikm.net/" },
    { title: "nxbrew-Switch", href: "https://nxbrew.com/category/games/switch-nsp/" },
    { title: "SwitcheShop(NSP)", href: "https://madloader.com/nintendo-switch/switch-eshop-nsp/" },
    { title: "1fichier-Switch", href: "https://1fichier.com/dir/lnMt5OGF" },
    { title: "低端影视", href: "https://ddys.pro/" },
    { title: "freemagazinepdf", href: "https://freemagazinepdf.com/" },
    { title: "Switch攻略阁", href: "http://www.265xh.com/nszhinan/index_2.html" },
    { title: "Mixkit-视频素材、AE/PR模板", href: "https://mixkit.co/" },
    { title: "Azlyrics-音乐歌词", href: "https://www.azlyrics.com/" },
    { title: "有谱网", href: "https://yopu.co/start?mode=startup" },
    { title: "电视眼", href: "http://www.tvyan.com/" },
    { title: "mult-动画旅游地图", href: "https://mult.dev/zh" },
    { title: "WINOS", href: "https://www.winos.me/" },   
    { title: "创客贴", href: "https://www.chuangkit.com/designtools/startdesign" },
    { title: "MagicEraser-删除照片中的物体", href: "https://magicstudio.com/zh/magiceraser/" },   
    { title: "upscale-改变图片分辨率", href: "https://www.upscale.media/zh" },
    { title: "字由-字体", href: "https://www.hellofont.cn/home" },   
    { title: "MSDNItellU", href: "https://msdn.itellyou.cn/" },
    { title: "电子包浆-图片做旧", href: "https://magiconch.com/patina/" },
    { title: "接码号", href: "https://jiemahao.com/" },
    { title: "BridgeDB-Tor网桥", href: "https://bridges.torproject.org/" },
    { title: "remove-在线抠图", href: "https://www.remove.bg/zh" },
    { title: "photopea-在线PS", href: "https://www.photopea.com/" },
    { title: "openshot-视频编辑", href: "https://www.openshot.org/" },
    { title: "watermark-在线添加水印", href: "https://efrice.github.io/watermark/" },
    { title: "easygif-GIF编辑器", href: "https://www.easygif.tools/#/" },
    { title: "photoroom-图片背景去除", href: "https://www.photoroom.com/tools/background-remover" },
    { title: "unscreen-视频背景去除", href: "https://www.unscreen.com/" },
    { title: "mockuuups-海报设计", href: "https://mockuuups.studio/" },
    { title: "密钥分享", href: "https://webact.185.hk/sharedkey.php" },
    { title: "读者阁", href: "https://duzhege.cn/" },
    { title: "magazinelib", href: "https://magazinelib.com/" },
    { title: "freemagazines", href: "https://freemagazines.top/" },
    { title: "素颜blog", href: "https://www.suyanw.cn/" },
    { title: "微信截图生成", href: "https://ourboy.cn/dz/" },
    { title: "国内期刊", href: "http://qikan.lifves.com/" },
    { title: "IT技术之家", href: "https://www.ittel.cn/" },
    { title: "mefcl博客", href: "https://www.mefcl.com/" },
    { title: "影视动漫分享", href: "https://www.seedhub.cc/" },
    { title: "freemagazines", href: "https://www.freemagazines.best/" },
    { title: "极限游戏", href: "https://www.xgamefan.com/" },
    { title: "邮箱购买", href: "http://www.yxwwyx.com/" },
    { title: "直播源分享", href: "https://yang-1989.eu.org/" },
    { title: "123IPTV", href: "https://www.123iptv.tv/" },
    { title: "临时邮箱", href: "https://tempmail.so/#" },
    { title: "不死鸟", href: "https://iui.su/" },
    { title: "安卓应用分享", href: "https://www.iapps.me/" },
    { title: "pdfmagaz", href: "https://www.pdfmagaz.in/start/" },
    { title: "音乐仓库", href: "https://www.cangkus.com/" },
    { title: "LOGO厨师", href: "https://www.logocook.shop/" },
    { title: "临时Gmail邮箱", href: "https://freegmail.go24.info/" },
  ]
